Backout the effective part of r25113. It breaks parts of the code that *had* created a logger before the XPCOM-ified Logging class was added.
----
ERROR:xpcom:Unhandled exception calling 'int8 getLogger(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "/Users/trentm/as/komodo/mozilla/build/cvs-ko5.11-komoz511a/mozilla/ko-rel-ns-ns-tools/dist/Komodo.app/Contents/MacOS/python/xpcom/server/__init__.py", line 64, in WrapObject
    return _xpcom.WrapObject(policy( ob, iid ), iid, bWrapClient)
  File "/Users/trentm/as/komodo/mozilla/build/cvs-ko5.11-komoz511a/mozilla/ko-rel-ns-ns-tools/dist/Komodo.app/Contents/MacOS/python/xpcom/server/policy.py", line 145, in __init__
    raise ValueError, "The object '%r' can not be used as a COM object" % (instance,)
ValueError: The object '<logging.Logger instance at 0x142a77d8>' can not be used as a COM object
----

(integrated from komodo (trunk) change 25121 by trentm)

git-svn-id: http://svn.openkomodo.com/repos/openkomodo/trunk@2687 b87d16e7-d29f-4ee1-b5ec-817d645d335f